# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        type: [Type1, Type2, Type3]
        include:
          - type: Type1
            drop: drop1
            type1: 0
            agent: '["linux-latest"]'
          - type: Type2
            drop: drop2
            agent: '["linux-latest"]'
    name: ${{ matrix.type }}
    runs-on: ${{ fromJSON(matrix.agent) }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Drop ${{ matrix.drop }}
        run: echo Hello, world ${{ matrix.drop }}!
      - if: ${{ matrix.type == 'Type1' }}
        name: Run ${{ matrix.type }}
        uses: ./temp1.yml
        with:
          drop: ${{ matrix.drop }}
      - if: ${{ matrix.type == 'Type2' }}
        name: Run ${{ matrix.type }}
        uses: ./temp2.yml
        with:
          drop: ${{ matrix.drop }}
